config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :reviews

  get 'search_books/search'
  root 'pages#home'
  resources :users do
    member do
      get :mypage
      get :review_detail
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @reviews = Review.limit(10).order(created_at: :desc)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update]

  def new
    @review = Review.new
    @book_title = params[:review][:book_title]
    @book_author = params[:review][:book_author]
    @book_image_url = params[:review][:book_image_url]
    @reviewer = current_user.name
  end

  def create
    @review = current_user.reviews.build(review_params)
    if @review.save
      redirect_to root_path, notice: "レビューが作成されました"
    else
      render :new
    end
  end

  def show
    @review = Review.find(params[:id])
  end


  def destroy
    @review = current_user.reviews.find(params[:id])
    @review.destroy
    redirect_to mypage_user_path(current_user), notice: "レビューが削除されました"
  end

  def edit
    @review = Review.find(params[:id])
  end
  def update
    @review = Review.find(params[:id])
    if @review.update(review_params)
      redirect_to mypage_user_path(current_user), notice: "レビューが更新されました"
    else
      render :edit
    end
  end



  private

  def review_params
    params.require(:review).permit(:book_title, :book_author, :rating, :read_date, :content, :book_image_url, :reviewer, :user_id)
  end
end

app/controllers/search_books_controller.rb
class SearchBooksController < ApplicationController
  require 'net/http'
  require 'json'

  def search
    if params[:query].present?
      @query = params[:query]
      url = URI("https://www.googleapis.com/books/v1/volumes?q=#{URI.encode_www_form_component(@query)}")
      response = Net::HTTP.get(url)
      @results = JSON.parse(response)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:mypage, :review_detail]
  before_action :correct_user, only: [:review_detail]

  def mypage
    @user = current_user
    @reviews = @user.reviews
    @review = current_user.reviews.find_by(id: params[:review_id])
  end

  def review_detail
    @review = Review.find(params[:review_id])
  end

  private

  def correct_user
    @review = current_user.reviews.find_by(id: params[:review_id])
    redirect_to root_path, alert: "権限がありません" if @review.nil?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/search_books_helper.rb
module SearchBooksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bookhistory</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" rel="stylesheet">
  <%= javascript_importmap_tags %>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">
        <img src="/assets/logo.jpg" alt="ロゴ" width="30" height="24" class="d-inline-block align-text-top">
        BookHistory
      </a>
      <a class="navbar-brand" href="/">
        <i class="bi bi-house"></i>
      </a>
       <% if user_signed_in? %>
          <span class="navbar-text">
            <%= current_user.name %>でログイン中
          </span>
          <%= link_to "マイページ", mypage_user_path(current_user), class: "btn btn-outline-primary ms-2" %>
          <%= link_to "ログアウト", destroy_user_session_path, method: :get, class: "btn btn-outline-danger ms-2" %>
        <% else %>
          <%= link_to "ログイン", new_user_session_path, class: "btn btn-outline-success" %>
        <% end %>
        <%= link_to "本を探す", search_books_search_path, class: "btn btn-outline-info ms-auto" %>
      </div>
      
    </div>
  </nav>

  <div class="container my-4">
    <%= yield %>
  </div>

  <footer class="bg-light text-center py-3">
    <p>&copy; <%= Time.now.year %> Bookhistory. All rights reserved.</p>
  </footer>
</body>
</html>

app/views/pages/home.html.erb
<h2 class="mt-4 mb-3">最新のレビュー</h2>
<div class="row">
  <% @reviews.each do |review| %>
    <div class="col-md-6">
      <%= link_to review_path(review), class: "card mb-3" do %>
        <div class="card-body">
          <% if review.book_image_url.present? %>
            <%= image_tag review.book_image_url, class: "img-fluid mb-3" %>
          <% end %>
          <h3 class="card-title"><%= review.book_title %></h3>
          <p class="card-text"><strong>著者:</strong> <%= review.book_author %></p>
          <p class="card-text"><strong>投稿者:</strong> <%= review.reviewer %></p>
          <p class="card-text">
            <strong>評価:</strong> 
            <% 1.upto(5) do |star| %>
              <% if star <= review.rating %>
                <i class="fas fa-star"></i>
              <% else %>
                <i class="far fa-star"></i>
              <% end %>
            <% end %>
          </p>
          <p class="card-text"><strong>読了日:</strong> <%= review.read_date %></p>
          <p class="card-text"><strong>レビュー内容:</strong> <%= review.content %></p>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/edit.html.erb
<h1>レビューを編集する</h1>

<% if @review.book_image_url.present? %>
  <%= image_tag @review.book_image_url, class: "img-fluid mb-3" %>
<% end %>
<h2 class="mb-2"><%= @review.book_title %></h2>
<p class="mb-4"><strong>著者:</strong> <%= @review.book_author %></p>

<%= form_with(model: @review, url: review_path(@review), method: :patch, html: { class: 'needs-validation', novalidate: '' }) do |form| %>
  <% if @review.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
        <% @review.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :reviewer, value: current_user.name %>
  <%= form.hidden_field :book_title, value: @review.book_title %>
  <%= form.hidden_field :book_author, value: @review.book_author %>
  <div class="form-group mb-3">
    <%= form.label "評価", class: 'form-label' %>
    <%= form.select :rating, (1..5), { selected: @review.rating }, { class: 'form-select' } %>
  </div>

  <div class="form-group mb-3">
    <%= form.label "読了日", class: 'form-label' %>
    <%= form.date_field :read_date, value: @review.read_date, class: 'form-control' %>
  </div>

  <div class="form-group mb-3">
    <%= form.label "レビュー", class: 'form-label' %>
    <%= form.text_area :content, value: @review.content, class: 'form-control' %>
  </div>

  <div class="d-none">
    <%= form.hidden_field :book_image_url, value: @review.book_image_url %>
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>

  <div class="actions mt-3">
    <%= form.submit "更新する", class: 'btn btn-primary' %>
  </div>
<% end %>

<%= link_to "キャンセル", mypage_user_path(current_user), class: 'btn btn-secondary mt-2' %>

app/views/reviews/new.html.erb
<% if @book_image_url.present? %>
  <%= image_tag @book_image_url, class: "img-fluid mb-3" %>
<% end %>
<h1><%= @book_title %>のレビュー</h1>
<h4>著者: <%= @book_author %></h4>


<%= form_with(model: @review, url: reviews_path, method: :post, class: "needs-validation", novalidate: true) do |form| %>
  <% if @review.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
        <% @review.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :reviewer, value: current_user.name %>
  <%= form.hidden_field :book_title, value: @book_title %>
  <%= form.hidden_field :book_author, value: @book_author %>

  <div class="mb-3">
    <%= form.label :rating, class: "form-label" %>
    <%= form.select :rating, (1..5), {}, { class: "form-select" } %>
  </div>

  <div class="mb-3">
    <%= form.label :read_date, class: "form-label" %>
    <%= form.date_field :read_date, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :content, class: "form-label" %>
    <%= form.text_area :content, class: "form-control" %>
  </div>

  <%= form.hidden_field :book_image_url, value: @book_image_url %>
  <%= form.hidden_field :user_id, value: current_user.id %>

  <div class="mb-3">
    <%= form.submit "レビューを作成する", class: "btn btn-primary" %>
  </div>
<% end %>

<%= link_to "キャンセル", root_path, class: "btn btn-secondary" %>

app/views/reviews/show.html.erb
<div class="card mb-4">
  <div class="card-body">
    <%= image_tag @review.book_image_url, class: "img-fluid" %>
    <h2 class="card-title"><%= @review.book_title %></h2>
    <p class="card-text"><strong>著者:</strong> <%= @review.book_author %></p>
    <p class="card-text"><strong>評価:</strong> <%= @review.rating %></p>
    <p class="card-text"><strong>投稿者:</strong> <%= @review.reviewer %></p>
    <p class="card-text"><strong>読了日:</strong> <%= @review.read_date %></p>
    <p class="card-text"><strong>レビュー:</strong> <%= @review.content %></p>
  </div>
</div>


<%= link_to "一覧に戻る", root_path, class: "btn btn-secondary" %>

app/views/search_books/search.html.erb
<h1>本を検索</h1>

<%= form_tag search_books_search_path, method: :get, class: "form-inline my-4" do %>
  <%= text_field_tag :query, params[:query], placeholder: "検索語句を入力してください", class: "form-control mr-2" %>
  <%= submit_tag "検索", class: "btn btn-primary" %>
<% end %>

<% if @results.present? %>
  <h2 class="mt-4">検索結果</h2>
  <% @results["items"].each do |item| %>
    <% if item["volumeInfo"].present? && item["volumeInfo"]["title"].present? && item["volumeInfo"]["authors"].present? && item["volumeInfo"]["imageLinks"].present? %>
      <div class="card mb-3">
        <div class="card-body">
          <h3 class="card-title"><%= item["volumeInfo"]["title"] %></h3>
          <%= image_tag item["volumeInfo"]["imageLinks"]["thumbnail"], class: "img-fluid" %>
          <p class="card-text">著者: <%= item["volumeInfo"]["authors"].join(", ") %></p>
          <%= link_to "レビューを作成する", new_review_path(review: { book_title: item["volumeInfo"]["title"], book_author: item["volumeInfo"]["authors"].join(", "), book_image_url: item["volumeInfo"]["imageLinks"]["thumbnail"] }), class: "btn btn-outline-secondary" %>
        </div>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/users/mypage.html.erb
<h1>マイページ</h1>

<h2 class="mt-4 mb-3">投稿したレビュー一覧</h2>
<div class="row">
  <% @reviews.each do |review| %>
    <div class="col-md-6">
      <%= link_to review_detail_user_path(@user, review_id: review.id), class: "card mb-3" do %>
        <div class="card-body">
          <% if review.book_image_url.present? %>
            <%= image_tag review.book_image_url, class: "img-fluid mb-3" %>
          <% end %>
          <h3 class="card-title"><%= review.book_title %></h3>
          <p class="card-text"><strong>著者:</strong> <%= review.book_author %></p>
          <p class="card-text"><strong>評価:</strong> <%= review.rating %></p>
          <p class="card-text"><strong>読了日:</strong> <%= review.read_date %></p>
          <p class="card-text"><strong>内容:</strong> <%= review.content %></p>
          <%= button_to "削除", review_path(review.id), method: :delete, data: { confirm: "本当に削除しますか？" }, class: "btn btn-danger" %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/users/review_detail.html.erb
<h1><%= @review.book_title %></h1>
<p><strong>著者:</strong> <%= @review.book_author %></p>
<p><strong>評価:</strong> <%= @review.rating %></p>
<p><strong>読了日:</strong> <%= @review.read_date %></p>
<p><strong>内容:</strong> <%= @review.content %></p>
<%= link_to "編集", edit_review_path(@review), class: "btn btn-primary" %>
<%= button_to "削除", review_path(@review), method: :delete, data: { confirm: "本当に削除しますか？" }, class: "btn btn-danger" %>